### PR TITLE
Add support for timeouts

### PR DESCRIPTION
**Pull request by sjerman**
Hi.

I needed to be able to adjust the HTTPS client timeouts and this was the suggested approach.

Not sure if you want or not but thought I would offer...

Steve

### CODE REVIEW

**Comment by miwurster** [comment]
Hey! Thanks for the implementation. I'll definitely merge your PR into master ... but, would it be possible to reformat your PR based on the source code formatting of the current master? Just to avoid changes due to different formatters... ;-) Thanks!

**Comment by sjerman** [comment]
OK done....

**Comment by sjerman** [comment]
reformatted

**Comment by sjerman** [comment]
One request :) .... if/when you merge this .... could you do a release.

**Comment by miwurster** [comment]
I've released the library... Should be available in [Maven Central](https://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22com.github.miwurster%22%20AND%20a%3A%22spring-data-influxdb%22) very soon.

**Comment by sjerman** [comment]
Thanks.

**Pull request merged**
